/**
 *
 * $Id$
 */
package org.palladiosimulator.dependability.reliability.uncertainty.validation;

import org.eclipse.emf.common.util.EList;

import org.palladiosimulator.dependability.reliability.uncertainty.MapEntry;

/**
 * A sample validator interface for {@link org.palladiosimulator.dependability.reliability.uncertainty.DeterministicImprovement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface DeterministicImprovementValidator {
	boolean validate();

	boolean validateMappingTable(EList<MapEntry> value);
}
