/**
 *
 * $Id$
 */
package org.palladiosimulator.dependability.reliability.uncertainty.validation;

import tools.mdsd.probdist.distributionfunction.ProbabilityDistribution;

/**
 * A sample validator interface for {@link org.palladiosimulator.dependability.reliability.uncertainty.ProbabilisticImprovement}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface ProbabilisticImprovementValidator {
	boolean validate();

	boolean validateProbabilityDistribution(ProbabilityDistribution value);
}
