/**
 *
 * $Id$
 */
package org.palladiosimulator.dependability.reliability.uncertainty.validation;

import org.palladiosimulator.dependability.reliability.uncertainty.UncertaintyImprovement;

import org.palladiosimulator.envdyn.environment.templatevariable.TemplateVariable;

/**
 * A sample validator interface for {@link org.palladiosimulator.dependability.reliability.uncertainty.UncertaintySpecificCountermeasure}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface UncertaintySpecificCountermeasureValidator {
	boolean validate();

	boolean validateTargetUncertainty(TemplateVariable value);

	boolean validateUncertaintyImprovement(UncertaintyImprovement value);
}
