/**
 */
package org.palladiosimulator.dependability.reliability.uncertainty.provider;

import java.util.ArrayList;
import java.util.Collection;

import org.eclipse.emf.common.notify.Adapter;
import org.eclipse.emf.common.notify.Notification;
import org.eclipse.emf.common.notify.Notifier;

import org.eclipse.emf.edit.provider.ChangeNotifier;
import org.eclipse.emf.edit.provider.ComposeableAdapterFactory;
import org.eclipse.emf.edit.provider.ComposedAdapterFactory;
import org.eclipse.emf.edit.provider.IChangeNotifier;
import org.eclipse.emf.edit.provider.IDisposable;
import org.eclipse.emf.edit.provider.IEditingDomainItemProvider;
import org.eclipse.emf.edit.provider.IItemLabelProvider;
import org.eclipse.emf.edit.provider.IItemPropertySource;
import org.eclipse.emf.edit.provider.INotifyChangedListener;
import org.eclipse.emf.edit.provider.IStructuredItemContentProvider;
import org.eclipse.emf.edit.provider.ITreeItemContentProvider;

import org.palladiosimulator.dependability.reliability.uncertainty.util.UncertaintyAdapterFactory;

/**
 * This is the factory that is used to provide the interfaces needed to support Viewers.
 * The adapters generated by this factory convert EMF adapter notifications into calls to {@link #fireNotifyChanged fireNotifyChanged}.
 * The adapters also support Eclipse property sheets.
 * Note that most of the adapters are shared among multiple instances.
 * <!-- begin-user-doc -->
 * <!-- end-user-doc -->
 * @generated
 */
public class UncertaintyItemProviderAdapterFactory extends UncertaintyAdapterFactory
		implements ComposeableAdapterFactory, IChangeNotifier, IDisposable {
	/**
	 * This keeps track of the root adapter factory that delegates to this adapter factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ComposedAdapterFactory parentAdapterFactory;

	/**
	 * This is used to implement {@link org.eclipse.emf.edit.provider.IChangeNotifier}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected IChangeNotifier changeNotifier = new ChangeNotifier();

	/**
	 * This keeps track of all the supported types checked by {@link #isFactoryForType isFactoryForType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected Collection<Object> supportedTypes = new ArrayList<Object>();

	/**
	 * This constructs an instance.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	public UncertaintyItemProviderAdapterFactory() {
		supportedTypes.add(IEditingDomainItemProvider.class);
		supportedTypes.add(IStructuredItemContentProvider.class);
		supportedTypes.add(ITreeItemContentProvider.class);
		supportedTypes.add(IItemLabelProvider.class);
		supportedTypes.add(IItemPropertySource.class);
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.dependability.reliability.uncertainty.UncertaintyInducedFailureType} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UncertaintyInducedFailureTypeItemProvider uncertaintyInducedFailureTypeItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.dependability.reliability.uncertainty.UncertaintyInducedFailureType}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUncertaintyInducedFailureTypeAdapter() {
		if (uncertaintyInducedFailureTypeItemProvider == null) {
			uncertaintyInducedFailureTypeItemProvider = new UncertaintyInducedFailureTypeItemProvider(this);
		}

		return uncertaintyInducedFailureTypeItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.dependability.reliability.uncertainty.UncertaintyRepository} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UncertaintyRepositoryItemProvider uncertaintyRepositoryItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.dependability.reliability.uncertainty.UncertaintyRepository}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUncertaintyRepositoryAdapter() {
		if (uncertaintyRepositoryItemProvider == null) {
			uncertaintyRepositoryItemProvider = new UncertaintyRepositoryItemProvider(this);
		}

		return uncertaintyRepositoryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.dependability.reliability.uncertainty.ActiveComponent} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ActiveComponentItemProvider activeComponentItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.dependability.reliability.uncertainty.ActiveComponent}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createActiveComponentAdapter() {
		if (activeComponentItemProvider == null) {
			activeComponentItemProvider = new ActiveComponentItemProvider(this);
		}

		return activeComponentItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.dependability.reliability.uncertainty.DeterministicImprovement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected DeterministicImprovementItemProvider deterministicImprovementItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.dependability.reliability.uncertainty.DeterministicImprovement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createDeterministicImprovementAdapter() {
		if (deterministicImprovementItemProvider == null) {
			deterministicImprovementItemProvider = new DeterministicImprovementItemProvider(this);
		}

		return deterministicImprovementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.dependability.reliability.uncertainty.ProbabilisticImprovement} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected ProbabilisticImprovementItemProvider probabilisticImprovementItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.dependability.reliability.uncertainty.ProbabilisticImprovement}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createProbabilisticImprovementAdapter() {
		if (probabilisticImprovementItemProvider == null) {
			probabilisticImprovementItemProvider = new ProbabilisticImprovementItemProvider(this);
		}

		return probabilisticImprovementItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.dependability.reliability.uncertainty.MapEntry} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected MapEntryItemProvider mapEntryItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.dependability.reliability.uncertainty.MapEntry}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createMapEntryAdapter() {
		if (mapEntryItemProvider == null) {
			mapEntryItemProvider = new MapEntryItemProvider(this);
		}

		return mapEntryItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.dependability.reliability.uncertainty.UncertaintySpecificCountermeasure} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UncertaintySpecificCountermeasureItemProvider uncertaintySpecificCountermeasureItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.dependability.reliability.uncertainty.UncertaintySpecificCountermeasure}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUncertaintySpecificCountermeasureAdapter() {
		if (uncertaintySpecificCountermeasureItemProvider == null) {
			uncertaintySpecificCountermeasureItemProvider = new UncertaintySpecificCountermeasureItemProvider(this);
		}

		return uncertaintySpecificCountermeasureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.dependability.reliability.uncertainty.GlobalUncertaintyCountermeasure} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected GlobalUncertaintyCountermeasureItemProvider globalUncertaintyCountermeasureItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.dependability.reliability.uncertainty.GlobalUncertaintyCountermeasure}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createGlobalUncertaintyCountermeasureAdapter() {
		if (globalUncertaintyCountermeasureItemProvider == null) {
			globalUncertaintyCountermeasureItemProvider = new GlobalUncertaintyCountermeasureItemProvider(this);
		}

		return globalUncertaintyCountermeasureItemProvider;
	}

	/**
	 * This keeps track of the one adapter used for all {@link org.palladiosimulator.dependability.reliability.uncertainty.UncertaintyModelEquality} instances.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	protected UncertaintyModelEqualityItemProvider uncertaintyModelEqualityItemProvider;

	/**
	 * This creates an adapter for a {@link org.palladiosimulator.dependability.reliability.uncertainty.UncertaintyModelEquality}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter createUncertaintyModelEqualityAdapter() {
		if (uncertaintyModelEqualityItemProvider == null) {
			uncertaintyModelEqualityItemProvider = new UncertaintyModelEqualityItemProvider(this);
		}

		return uncertaintyModelEqualityItemProvider;
	}

	/**
	 * This returns the root adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public ComposeableAdapterFactory getRootAdapterFactory() {
		return parentAdapterFactory == null ? this : parentAdapterFactory.getRootAdapterFactory();
	}

	/**
	 * This sets the composed adapter factory that contains this factory.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void setParentAdapterFactory(ComposedAdapterFactory parentAdapterFactory) {
		this.parentAdapterFactory = parentAdapterFactory;
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public boolean isFactoryForType(Object type) {
		return supportedTypes.contains(type) || super.isFactoryForType(type);
	}

	/**
	 * This implementation substitutes the factory itself as the key for the adapter.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Adapter adapt(Notifier notifier, Object type) {
		return super.adapt(notifier, this);
	}

	/**
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public Object adapt(Object object, Object type) {
		if (isFactoryForType(type)) {
			Object adapter = super.adapt(object, type);
			if (!(type instanceof Class<?>) || (((Class<?>) type).isInstance(adapter))) {
				return adapter;
			}
		}

		return null;
	}

	/**
	 * This adds a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void addListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.addListener(notifyChangedListener);
	}

	/**
	 * This removes a listener.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void removeListener(INotifyChangedListener notifyChangedListener) {
		changeNotifier.removeListener(notifyChangedListener);
	}

	/**
	 * This delegates to {@link #changeNotifier} and to {@link #parentAdapterFactory}.
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void fireNotifyChanged(Notification notification) {
		changeNotifier.fireNotifyChanged(notification);

		if (parentAdapterFactory != null) {
			parentAdapterFactory.fireNotifyChanged(notification);
		}
	}

	/**
	 * This disposes all of the item providers created by this factory. 
	 * <!-- begin-user-doc -->
	 * <!-- end-user-doc -->
	 * @generated
	 */
	@Override
	public void dispose() {
		if (uncertaintyInducedFailureTypeItemProvider != null)
			uncertaintyInducedFailureTypeItemProvider.dispose();
		if (uncertaintyRepositoryItemProvider != null)
			uncertaintyRepositoryItemProvider.dispose();
		if (activeComponentItemProvider != null)
			activeComponentItemProvider.dispose();
		if (deterministicImprovementItemProvider != null)
			deterministicImprovementItemProvider.dispose();
		if (probabilisticImprovementItemProvider != null)
			probabilisticImprovementItemProvider.dispose();
		if (mapEntryItemProvider != null)
			mapEntryItemProvider.dispose();
		if (uncertaintySpecificCountermeasureItemProvider != null)
			uncertaintySpecificCountermeasureItemProvider.dispose();
		if (globalUncertaintyCountermeasureItemProvider != null)
			globalUncertaintyCountermeasureItemProvider.dispose();
		if (uncertaintyModelEqualityItemProvider != null)
			uncertaintyModelEqualityItemProvider.dispose();
	}

}
